language: php

php:
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - COMPOSER_OPTIONS=""

before_install:
  - sudo apt-get update
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_OPTIONS} --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)